channels:
- name: Lex Fridman Podcast
  channel_id: UCSHZKyawb77ixDdsGog4iWA
  category: ai-interviews
- name: No Priors
  channel_id: UCSI7h9hydQ40K5MJHnCrQvw
  category: ai-vc
- name: Y Combinator
  channel_id: UCcefcZRL2oaA_uBNeo5UOWg
  handle: '@ycombinator'
  category: general
- name: Lenny's Podcast
  channel_id: UC6t1O76G0jYXOAoYCm153dA
  handle: '@LennysPodcast'
  category: general
- name: Last Week in AI
  channel_id: UCKARTq-t5SPMzwtft8FWwnA
  handle: '@lastweekinai'
  category: ai-news
- name: Dwarkesh Patel
  channel_id: UCXl4i9dYBrFOabk0xGmbkRA
  category: ai-interviews
  handle: '@DwarkeshPatel'
- name: Acquired
  channel_id: UCyFqFYfTW2VoIQKylJ04Rtw
  category: general
  handle: '@AcquiredFM'
- name: Bg2 Pod
  channel_id: UC-yRDvpR99LUc5l7i7jLzew
  category: ai-vc
  handle: '@Bg2Pod'
- name: Cognitive Revolution
  channel_id: UCjNRVMBVI30Sak_p6HRWhIA
  category: ai-explainer
  handle: '@CognitiveRevolutionPodcast'
- name: a16z
  channel_id: UC9cn0TuPq4dnbTY-CBsm8XA
  category: ai-vc
  handle: '@a16z'
- name: Latent Space
  channel_id: UCxBcwypKK-W3GHd_RZ9FZrQ
  category: ai-engineering
  handle: '@LatentSpacePod'
- name: AI Daily Brief
  channel_id: UCKelCK4ZaO6HeEI1KQjqzWA
  category: ai-news
  handle: '@AIDailyBrief'
- name: All-In Podcast
  channel_id: UCESLZhusAkFfsNsApnjF_Cg
  category: ai-vc
  handle: '@allin'
- name: 20VC
  channel_id: UCf0PBRjhf0rF8fWBIxTuoWA
  category: ai-vc
  handle: '@20VC'
- name: Hard Fork
  channel_id: UCZcR2SVWaGWNlMqPxvQS3vw
  category: ai-news
  handle: '@hardfork'
- name: Moment of Zen
  channel_id: UCY0OE_54Viqx_qtXuh-85VA
  category: ai-vc
  handle: '@MomentofZenPodcast'
- name: The Logan Bartlett Show
  channel_id: UCugS0jD5IAdoqzjaNYzns7w
  category: ai-vc
  handle: '@theloganbartlettshow'
- name: Machine Learning Street Talk
  channel_id: UCMLtBahI5DMrt0NPvDSoIRQ
  category: ai-explainer
  handle: '@MachineLearningStreetTalk'
